spring:
  cache:
    type: caffeine # 캐시 제공자 설정 (Caffeine을 사용한다고 가정)
    caffeine:
      spec: expireAfterAccess=12h,maximumSize=1000
  datasource:
    url: jdbc:mysql://220.93.95.108:3306/shoppingmall
    username: ksubin
    password: 1396
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true


upload:
  path: /home/ksubin/shoppingmall/photo/

server:
  port: 8090

