spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping-mall
    username: ksubin
    password: 1396
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true


upload:
  path: D:/Intellij/workspace/shopping-mall/src/main/resources/static/images/

server:
  port: 8090

